spring:
  application:
    name: shop-service
  data:
    mongodb:
      database: shop
      authentication-database: admin
      host: localhost
      port: 27092
      username: admin
      password: password
      auto-index-creation: true

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
