spring:
  application:
    name: shop-service
  data:
    mongodb:
      database: shop
      authentication-database: admin
      host: localhost
      port: 27092
      username: admin
      password: password
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka/}
      instance:
        prefer-ip-address: true