spring:
  application:
    name: notification-service
  data:
    mongodb:
      database: notification
      authentication-database: admin
      host: localhost
      port: 27093
      username: admin
      password: password
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8093

eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
