apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      name: api-gateway-service
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: giuliaqqrd/apigateway:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVER
              value: "http://discovery-service:8761/eureka/"
      restartPolicy: Always
      