apiVersion: v1
kind: Service
metadata:
  name: mongo-notification
  labels:
    app: mongo-notification
spec:
  selector:
    app: mongo-notification
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

  