spring:
  application:
    name: user-service
  data:
    mongodb:
      database: user
      authentication-database: admin
      host: localhost
      port: 27090
      username: admin
      password: password
      auto-index-creation: true


server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka/}
      instance:
        prefer-ip-address: true

