spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      mvc:
        routes:
         - id: discovery-service
           uri: lb://discovery-service
           predicates:
             - Path=/eureka/web
           filters:
             - SetPath=/

         - id: discovery-service-static
           uri: lb://discovery-service
           predicates:
             - Path=/eureka/**

         - id: user-service
           uri: lb://user-service
           predicates:
             - Path=/api/user/**

         - id: company-service
           uri: lb://company-service
           predicates:
             - Path=/api/company/**

         - id: shop-service
           uri: lb://shop-service
           predicates:
             - Path=/api/shop/**

         - id: notification-service
           uri: lb://notification-service
           predicates:
             - Path=/api/notification/**

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka/}

